jobs:
  - name: daily
    targetName: dev
    schedule: 0 12 * * *
    timeout: 2h30m
    steps:
      - name: run models
        command: dbt run
      - name: test models
        command: dbt test
      - name: execute SQL
        command: |
          WITH CTE AS (
            SELECT * FROM {{ source('Fivetran1', 'ORDERS') }}
          ),
          Final AS (
            SELECT * FROM CTE WHERE ROW_ID = '9'
          )
          SELECT * FROM Final
